// Package expr provides DynamoDB expression building with automatic
// reserved-word escaping via ExpressionAttributeNames.
package expr

// reservedWords is the set of DynamoDB reserved words that must be escaped
// with ExpressionAttributeNames when used as attribute names.
var reservedWords = map[string]bool{
	"abort": true, "absolute": true, "action": true, "add": true, "after": true,
	"agent": true, "all": true, "allocate": true, "alter": true, "analyze": true,
	"and": true, "any": true, "archive": true, "are": true, "array": true,
	"as": true, "asc": true, "ascii": true, "asensitive": true, "assertion": true,
	"asymmetric": true, "at": true, "atomic": true, "attach": true,
	"authorization": true, "authorize": true, "auto": true, "avg": true,
	"back": true, "backup": true, "base": true, "batch": true, "before": true,
	"begin": true, "between": true, "bigint": true, "binary": true, "bit": true,
	"blob": true, "block": true, "boolean": true, "both": true, "breadth": true,
	"bucket": true, "bulk": true, "by": true, "byte": true,
	"call": true, "called": true, "calling": true, "capacity": true,
	"cascade": true, "case": true, "cast": true, "catalog": true,
	"char": true, "character": true, "check": true, "class": true,
	"clob": true, "close": true, "cluster": true, "clustered": true,
	"coalesce": true, "collate": true, "collation": true, "column": true,
	"columns": true, "combine": true, "comment": true, "commit": true,
	"compact": true, "compile": true, "compress": true, "condition": true,
	"conflict": true, "connect": true, "connection": true, "consistency": true,
	"consistent": true, "constraint": true, "constraints": true,
	"constructor": true, "consumed": true, "continue": true, "convert": true,
	"copy": true, "corresponding": true, "count": true, "counter": true,
	"create": true, "cross": true, "cube": true, "current": true,
	"cursor": true, "cycle": true,
	"data": true, "database": true, "date": true, "datetime": true,
	"day": true, "deallocate": true, "dec": true, "decimal": true,
	"declare": true, "default": true, "deferrable": true, "deferred": true,
	"define": true, "defined": true, "definition": true, "delete": true,
	"delimiter": true, "delimiters": true, "deref": true, "desc": true,
	"describe": true, "descriptor": true, "detach": true, "deterministic": true,
	"diagnostics": true, "directories": true, "disable": true, "disconnect": true,
	"distinct": true, "distribute": true, "do": true, "double": true,
	"drop": true, "dump": true, "duration": true, "dynamic": true,
	"each": true, "element": true, "else": true, "elseif": true, "empty": true,
	"enable": true, "encoding": true, "end": true, "equals": true, "error": true,
	"escape": true, "evaluate": true, "exceeded": true, "except": true,
	"exception": true, "exceptions": true, "exclusive": true, "exec": true,
	"execute": true, "exists": true, "exit": true, "explain": true,
	"explode": true, "export": true, "expression": true, "extended": true,
	"external": true,
	"false": true, "family": true, "fetch": true, "fields": true, "file": true,
	"filter": true, "filtering": true, "final": true, "finish": true,
	"first": true, "fixed": true, "flattern": true, "float": true,
	"for": true, "force": true, "foreign": true, "format": true,
	"forward": true, "found": true, "free": true, "from": true,
	"full": true, "function": true, "functions": true,
	"general": true, "generate": true, "get": true, "glob": true,
	"global": true, "go": true, "goto": true, "grant": true, "greater": true,
	"group": true, "grouping": true,
	"handler": true, "hash": true, "have": true, "having": true,
	"heap": true, "hidden": true, "hold": true, "hour": true,
	"identified": true, "identity": true, "if": true, "ignore": true,
	"immediate": true, "import": true, "in": true, "including": true,
	"inclusive": true, "increment": true, "index": true, "infinite": true,
	"initially": true, "inline": true, "inner": true, "input": true,
	"insensitive": true, "insert": true, "instead": true, "int": true,
	"integer": true, "intersect": true, "interval": true, "into": true,
	"is": true, "isolation": true,
	"item": true, "items": true,
	"iterate": true,
	"join": true,
	"key": true, "keys": true,
	"lag": true, "language": true, "large": true, "last": true,
	"lateral": true, "lead": true, "leading": true, "leave": true,
	"left": true, "length": true, "less": true, "level": true, "like": true,
	"limit": true, "limited": true, "lists": true, "load": true,
	"local": true, "localtime": true, "localtimestamp": true, "location": true,
	"locator": true, "lock": true, "loop": true,
	"map": true, "match": true, "materialized": true, "max": true,
	"maxlen": true, "merge": true, "method": true, "metrics": true,
	"min": true, "minus": true, "minute": true, "missing": true,
	"mod": true, "mode": true, "modifies": true, "modify": true,
	"module": true, "month": true, "multi": true, "multiset": true,
	"name": true, "names": true, "national": true, "natural": true,
	"nchar": true, "new": true, "next": true, "no": true,
	"none": true, "not": true, "nothing": true, "null": true,
	"nullif": true, "number": true, "numeric": true,
	"object": true, "of": true, "offline": true, "offset": true,
	"old": true, "on": true, "online": true, "only": true, "open": true,
	"or": true, "order": true, "ordinality": true, "other": true,
	"out": true, "outer": true, "output": true, "over": true,
	"overlaps": true, "override": true,
	"owner": true,
	"partial": true, "partition": true, "partitions": true, "path": true,
	"percent": true, "percentile": true, "permission": true, "permissions": true,
	"pipe": true, "pipelined": true, "pivot": true, "placeholder": true,
	"position": true, "primary": true, "print": true, "prior": true,
	"private": true, "privileges": true, "procedure": true, "processed": true,
	"project": true, "projection": true, "property": true,
	"provisioning": true, "public": true, "put": true,
	"query": true, "quit": true,
	"range": true, "rank": true, "raw": true, "read": true, "reads": true,
	"real": true, "recursive": true, "reduce": true, "ref": true,
	"reference": true, "references": true, "referencing": true,
	"regexp": true, "region": true, "reindex": true, "rename": true,
	"repeat": true, "replace": true, "request": true, "reset": true,
	"resignal": true, "resource": true, "response": true, "restore": true,
	"restrict": true, "result": true, "return": true, "returning": true,
	"returns": true, "reverse": true, "right": true, "role": true,
	"rollback": true, "rollup": true, "routine": true, "row": true,
	"rows": true, "rule": true,
	"savepoint": true, "scan": true, "schema": true, "scope": true,
	"scroll": true, "search": true, "second": true, "section": true,
	"select": true, "sensitive": true, "sequence": true, "serializable": true,
	"session": true, "set": true, "sets": true, "shard": true,
	"show": true, "signal": true, "similar": true, "size": true,
	"smallint": true, "snapshot": true, "some": true, "source": true,
	"space": true, "specific": true, "specifictype": true, "split": true,
	"sql": true, "sqlcode": true, "sqlerror": true, "sqlexception": true,
	"sqlstate": true, "sqlwarning": true, "start": true, "state": true,
	"static": true, "status": true, "storage": true, "store": true,
	"stored": true, "stream": true, "string": true, "submultiset": true,
	"substring": true, "sum": true, "symmetric": true, "system": true,
	"table": true, "tablesample": true, "tag": true, "tags": true,
	"temporary": true, "terminated": true, "text": true, "than": true,
	"then": true, "time": true, "timestamp": true, "timezone": true,
	"to": true, "token": true, "total": true, "touch": true,
	"trailing": true, "transaction": true, "transform": true,
	"translate": true, "translation": true, "treat": true, "trigger": true,
	"trim": true, "true": true, "truncate": true, "ttl": true, "tuple": true,
	"type": true, "under": true, "undo": true, "union": true, "unique": true,
	"unit": true, "unknown": true, "unlogged": true, "unnest": true,
	"unpivot": true, "until": true, "update": true, "usage": true,
	"use": true, "user": true, "using": true,
	"value": true, "values": true, "varchar": true, "variable": true,
	"variance": true, "version": true, "view": true, "views": true,
	"virtual": true,
	"when": true, "where": true, "while": true, "window": true,
	"with": true, "within": true, "without": true, "work": true,
	"write": true, "year": true, "zone": true,
}

// IsReserved reports whether word is a DynamoDB reserved word.
// The check is case-insensitive.
func IsReserved(word string) bool {
	lower := toLower(word)
	return reservedWords[lower]
}

func toLower(s string) string {
	b := make([]byte, len(s))
	for i := range s {
		c := s[i]
		if c >= 'A' && c <= 'Z' {
			c += 'a' - 'A'
		}
		b[i] = c
	}
	return string(b)
}
